//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAExample.SRExample {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMsg", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RetCode {
            get {
                return this.RetCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RetCodeField, value) != true)) {
                    this.RetCodeField = value;
                    this.RaisePropertyChanged("RetCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RetMsg {
            get {
                return this.RetMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.RetMsgField, value) != true)) {
                    this.RetMsgField = value;
                    this.RaisePropertyChanged("RetMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object Obj {
            get {
                return this.ObjField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjField, value) != true)) {
                    this.ObjField = value;
                    this.RaisePropertyChanged("Obj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRExample.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WAExample.SRExample.HelloWorldResponse HelloWorld(WAExample.SRExample.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name param from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExampleData1", ReplyAction="*")]
        WAExample.SRExample.ExampleData1Response ExampleData1(WAExample.SRExample.ExampleData1Request request);
        
        // CODEGEN: Generating message contract since element name code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExampleData", ReplyAction="*")]
        WAExample.SRExample.ExampleDataResponse ExampleData(WAExample.SRExample.ExampleDataRequest request);
        
        // CODEGEN: Generating message contract since element name param from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExampleType", ReplyAction="*")]
        WAExample.SRExample.GetExampleTypeResponse GetExampleType(WAExample.SRExample.GetExampleTypeRequest request);
        
        // CODEGEN: Generating message contract since element name param from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExampleItem", ReplyAction="*")]
        WAExample.SRExample.GetExampleItemResponse GetExampleItem(WAExample.SRExample.GetExampleItemRequest request);
        
        // CODEGEN: Generating message contract since element name param1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPowerInfo", ReplyAction="*")]
        WAExample.SRExample.GetPowerInfoResponse GetPowerInfo(WAExample.SRExample.GetPowerInfoRequest request);
        
        // CODEGEN: Generating message contract since element name code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPowerInfo3", ReplyAction="*")]
        WAExample.SRExample.GetPowerInfo3Response GetPowerInfo3(WAExample.SRExample.GetPowerInfo3Request request);
        
        // CODEGEN: Generating message contract since element name code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExampleID", ReplyAction="*")]
        WAExample.SRExample.GetExampleIDResponse GetExampleID(WAExample.SRExample.GetExampleIDRequest request);
        
        // CODEGEN: Generating message contract since element name version from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIEVersionCount", ReplyAction="*")]
        WAExample.SRExample.GetIEVersionCountResponse GetIEVersionCount(WAExample.SRExample.GetIEVersionCountRequest request);
        
        // CODEGEN: Generating message contract since element name versionLevelFrom from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOldIEInfoList", ReplyAction="*")]
        WAExample.SRExample.GetOldIEInfoListResponse GetOldIEInfoList(WAExample.SRExample.GetOldIEInfoListRequest request);
        
        // CODEGEN: Generating message contract since element name versionLevelFrom from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIEVersionList", ReplyAction="*")]
        WAExample.SRExample.GetIEVersionListResponse GetIEVersionList(WAExample.SRExample.GetIEVersionListRequest request);
        
        // CODEGEN: Generating message contract since element name Code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrepareForIE8Downloading", ReplyAction="*")]
        WAExample.SRExample.PrepareForIE8DownloadingResponse PrepareForIE8Downloading(WAExample.SRExample.PrepareForIE8DownloadingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WAExample.SRExample.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WAExample.SRExample.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExampleData1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExampleData1", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.ExampleData1RequestBody Body;
        
        public ExampleData1Request() {
        }
        
        public ExampleData1Request(WAExample.SRExample.ExampleData1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleData1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param;
        
        public ExampleData1RequestBody() {
        }
        
        public ExampleData1RequestBody(string param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExampleData1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExampleData1Response", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.ExampleData1ResponseBody Body;
        
        public ExampleData1Response() {
        }
        
        public ExampleData1Response(WAExample.SRExample.ExampleData1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleData1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg ExampleData1Result;
        
        public ExampleData1ResponseBody() {
        }
        
        public ExampleData1ResponseBody(WAExample.SRExample.ResultMsg ExampleData1Result) {
            this.ExampleData1Result = ExampleData1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExampleDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExampleData", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.ExampleDataRequestBody Body;
        
        public ExampleDataRequest() {
        }
        
        public ExampleDataRequest(WAExample.SRExample.ExampleDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string param3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string supposedData;
        
        public ExampleDataRequestBody() {
        }
        
        public ExampleDataRequestBody(string code, string param1, string param2, string param3, string supposedData) {
            this.code = code;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.supposedData = supposedData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExampleDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExampleDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.ExampleDataResponseBody Body;
        
        public ExampleDataResponse() {
        }
        
        public ExampleDataResponse(WAExample.SRExample.ExampleDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg ExampleDataResult;
        
        public ExampleDataResponseBody() {
        }
        
        public ExampleDataResponseBody(WAExample.SRExample.ResultMsg ExampleDataResult) {
            this.ExampleDataResult = ExampleDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExampleTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExampleType", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetExampleTypeRequestBody Body;
        
        public GetExampleTypeRequest() {
        }
        
        public GetExampleTypeRequest(WAExample.SRExample.GetExampleTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExampleTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param;
        
        public GetExampleTypeRequestBody() {
        }
        
        public GetExampleTypeRequestBody(string param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExampleTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExampleTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetExampleTypeResponseBody Body;
        
        public GetExampleTypeResponse() {
        }
        
        public GetExampleTypeResponse(WAExample.SRExample.GetExampleTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExampleTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg GetExampleTypeResult;
        
        public GetExampleTypeResponseBody() {
        }
        
        public GetExampleTypeResponseBody(WAExample.SRExample.ResultMsg GetExampleTypeResult) {
            this.GetExampleTypeResult = GetExampleTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExampleItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExampleItem", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetExampleItemRequestBody Body;
        
        public GetExampleItemRequest() {
        }
        
        public GetExampleItemRequest(WAExample.SRExample.GetExampleItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExampleItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param;
        
        public GetExampleItemRequestBody() {
        }
        
        public GetExampleItemRequestBody(string param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExampleItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExampleItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetExampleItemResponseBody Body;
        
        public GetExampleItemResponse() {
        }
        
        public GetExampleItemResponse(WAExample.SRExample.GetExampleItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExampleItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg GetExampleItemResult;
        
        public GetExampleItemResponseBody() {
        }
        
        public GetExampleItemResponseBody(WAExample.SRExample.ResultMsg GetExampleItemResult) {
            this.GetExampleItemResult = GetExampleItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPowerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPowerInfo", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetPowerInfoRequestBody Body;
        
        public GetPowerInfoRequest() {
        }
        
        public GetPowerInfoRequest(WAExample.SRExample.GetPowerInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPowerInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param1;
        
        public GetPowerInfoRequestBody() {
        }
        
        public GetPowerInfoRequestBody(string param1) {
            this.param1 = param1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPowerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPowerInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetPowerInfoResponseBody Body;
        
        public GetPowerInfoResponse() {
        }
        
        public GetPowerInfoResponse(WAExample.SRExample.GetPowerInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPowerInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg GetPowerInfoResult;
        
        public GetPowerInfoResponseBody() {
        }
        
        public GetPowerInfoResponseBody(WAExample.SRExample.ResultMsg GetPowerInfoResult) {
            this.GetPowerInfoResult = GetPowerInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPowerInfo3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPowerInfo3", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetPowerInfo3RequestBody Body;
        
        public GetPowerInfo3Request() {
        }
        
        public GetPowerInfo3Request(WAExample.SRExample.GetPowerInfo3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPowerInfo3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string supposedData;
        
        public GetPowerInfo3RequestBody() {
        }
        
        public GetPowerInfo3RequestBody(string code, string param1, string supposedData) {
            this.code = code;
            this.param1 = param1;
            this.supposedData = supposedData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPowerInfo3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPowerInfo3Response", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetPowerInfo3ResponseBody Body;
        
        public GetPowerInfo3Response() {
        }
        
        public GetPowerInfo3Response(WAExample.SRExample.GetPowerInfo3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPowerInfo3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg GetPowerInfo3Result;
        
        public GetPowerInfo3ResponseBody() {
        }
        
        public GetPowerInfo3ResponseBody(WAExample.SRExample.ResultMsg GetPowerInfo3Result) {
            this.GetPowerInfo3Result = GetPowerInfo3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExampleIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExampleID", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetExampleIDRequestBody Body;
        
        public GetExampleIDRequest() {
        }
        
        public GetExampleIDRequest(WAExample.SRExample.GetExampleIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExampleIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string supposedData;
        
        public GetExampleIDRequestBody() {
        }
        
        public GetExampleIDRequestBody(string code, string param1, string supposedData) {
            this.code = code;
            this.param1 = param1;
            this.supposedData = supposedData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExampleIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExampleIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetExampleIDResponseBody Body;
        
        public GetExampleIDResponse() {
        }
        
        public GetExampleIDResponse(WAExample.SRExample.GetExampleIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExampleIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg GetExampleIDResult;
        
        public GetExampleIDResponseBody() {
        }
        
        public GetExampleIDResponseBody(WAExample.SRExample.ResultMsg GetExampleIDResult) {
            this.GetExampleIDResult = GetExampleIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIEVersionCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIEVersionCount", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetIEVersionCountRequestBody Body;
        
        public GetIEVersionCountRequest() {
        }
        
        public GetIEVersionCountRequest(WAExample.SRExample.GetIEVersionCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIEVersionCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string version;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pageNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rowCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TimeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string supposedData;
        
        public GetIEVersionCountRequestBody() {
        }
        
        public GetIEVersionCountRequestBody(string version, string pageNum, string rowCount, string TimeStamp, string Sign, string supposedData) {
            this.version = version;
            this.pageNum = pageNum;
            this.rowCount = rowCount;
            this.TimeStamp = TimeStamp;
            this.Sign = Sign;
            this.supposedData = supposedData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIEVersionCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIEVersionCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetIEVersionCountResponseBody Body;
        
        public GetIEVersionCountResponse() {
        }
        
        public GetIEVersionCountResponse(WAExample.SRExample.GetIEVersionCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIEVersionCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg GetIEVersionCountResult;
        
        public GetIEVersionCountResponseBody() {
        }
        
        public GetIEVersionCountResponseBody(WAExample.SRExample.ResultMsg GetIEVersionCountResult) {
            this.GetIEVersionCountResult = GetIEVersionCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOldIEInfoListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOldIEInfoList", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetOldIEInfoListRequestBody Body;
        
        public GetOldIEInfoListRequest() {
        }
        
        public GetOldIEInfoListRequest(WAExample.SRExample.GetOldIEInfoListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOldIEInfoListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string versionLevelFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string versionLevelTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pageNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rowCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TimeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string supposedData;
        
        public GetOldIEInfoListRequestBody() {
        }
        
        public GetOldIEInfoListRequestBody(string versionLevelFrom, string versionLevelTo, string pageNum, string rowCount, string TimeStamp, string Sign, string supposedData) {
            this.versionLevelFrom = versionLevelFrom;
            this.versionLevelTo = versionLevelTo;
            this.pageNum = pageNum;
            this.rowCount = rowCount;
            this.TimeStamp = TimeStamp;
            this.Sign = Sign;
            this.supposedData = supposedData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOldIEInfoListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOldIEInfoListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetOldIEInfoListResponseBody Body;
        
        public GetOldIEInfoListResponse() {
        }
        
        public GetOldIEInfoListResponse(WAExample.SRExample.GetOldIEInfoListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOldIEInfoListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg GetOldIEInfoListResult;
        
        public GetOldIEInfoListResponseBody() {
        }
        
        public GetOldIEInfoListResponseBody(WAExample.SRExample.ResultMsg GetOldIEInfoListResult) {
            this.GetOldIEInfoListResult = GetOldIEInfoListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIEVersionListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIEVersionList", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetIEVersionListRequestBody Body;
        
        public GetIEVersionListRequest() {
        }
        
        public GetIEVersionListRequest(WAExample.SRExample.GetIEVersionListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIEVersionListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string versionLevelFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string versionLevelTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pageNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rowCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TimeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string supposedData;
        
        public GetIEVersionListRequestBody() {
        }
        
        public GetIEVersionListRequestBody(string versionLevelFrom, string versionLevelTo, string pageNum, string rowCount, string TimeStamp, string Sign, string supposedData) {
            this.versionLevelFrom = versionLevelFrom;
            this.versionLevelTo = versionLevelTo;
            this.pageNum = pageNum;
            this.rowCount = rowCount;
            this.TimeStamp = TimeStamp;
            this.Sign = Sign;
            this.supposedData = supposedData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIEVersionListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIEVersionListResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.GetIEVersionListResponseBody Body;
        
        public GetIEVersionListResponse() {
        }
        
        public GetIEVersionListResponse(WAExample.SRExample.GetIEVersionListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIEVersionListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg GetIEVersionListResult;
        
        public GetIEVersionListResponseBody() {
        }
        
        public GetIEVersionListResponseBody(WAExample.SRExample.ResultMsg GetIEVersionListResult) {
            this.GetIEVersionListResult = GetIEVersionListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrepareForIE8DownloadingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrepareForIE8Downloading", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.PrepareForIE8DownloadingRequestBody Body;
        
        public PrepareForIE8DownloadingRequest() {
        }
        
        public PrepareForIE8DownloadingRequest(WAExample.SRExample.PrepareForIE8DownloadingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrepareForIE8DownloadingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TimeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string supposedData;
        
        public PrepareForIE8DownloadingRequestBody() {
        }
        
        public PrepareForIE8DownloadingRequestBody(string Code, string TimeStamp, string Sign, string supposedData) {
            this.Code = Code;
            this.TimeStamp = TimeStamp;
            this.Sign = Sign;
            this.supposedData = supposedData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrepareForIE8DownloadingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrepareForIE8DownloadingResponse", Namespace="http://tempuri.org/", Order=0)]
        public WAExample.SRExample.PrepareForIE8DownloadingResponseBody Body;
        
        public PrepareForIE8DownloadingResponse() {
        }
        
        public PrepareForIE8DownloadingResponse(WAExample.SRExample.PrepareForIE8DownloadingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrepareForIE8DownloadingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WAExample.SRExample.ResultMsg PrepareForIE8DownloadingResult;
        
        public PrepareForIE8DownloadingResponseBody() {
        }
        
        public PrepareForIE8DownloadingResponseBody(WAExample.SRExample.ResultMsg PrepareForIE8DownloadingResult) {
            this.PrepareForIE8DownloadingResult = PrepareForIE8DownloadingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WAExample.SRExample.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WAExample.SRExample.ServiceSoap>, WAExample.SRExample.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.HelloWorldResponse WAExample.SRExample.ServiceSoap.HelloWorld(WAExample.SRExample.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WAExample.SRExample.HelloWorldRequest inValue = new WAExample.SRExample.HelloWorldRequest();
            inValue.Body = new WAExample.SRExample.HelloWorldRequestBody();
            WAExample.SRExample.HelloWorldResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.ExampleData1Response WAExample.SRExample.ServiceSoap.ExampleData1(WAExample.SRExample.ExampleData1Request request) {
            return base.Channel.ExampleData1(request);
        }
        
        public WAExample.SRExample.ResultMsg ExampleData1(string param) {
            WAExample.SRExample.ExampleData1Request inValue = new WAExample.SRExample.ExampleData1Request();
            inValue.Body = new WAExample.SRExample.ExampleData1RequestBody();
            inValue.Body.param = param;
            WAExample.SRExample.ExampleData1Response retVal = ((WAExample.SRExample.ServiceSoap)(this)).ExampleData1(inValue);
            return retVal.Body.ExampleData1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.ExampleDataResponse WAExample.SRExample.ServiceSoap.ExampleData(WAExample.SRExample.ExampleDataRequest request) {
            return base.Channel.ExampleData(request);
        }
        
        public WAExample.SRExample.ResultMsg ExampleData(string code, string param1, string param2, string param3, string supposedData) {
            WAExample.SRExample.ExampleDataRequest inValue = new WAExample.SRExample.ExampleDataRequest();
            inValue.Body = new WAExample.SRExample.ExampleDataRequestBody();
            inValue.Body.code = code;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            inValue.Body.supposedData = supposedData;
            WAExample.SRExample.ExampleDataResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).ExampleData(inValue);
            return retVal.Body.ExampleDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.GetExampleTypeResponse WAExample.SRExample.ServiceSoap.GetExampleType(WAExample.SRExample.GetExampleTypeRequest request) {
            return base.Channel.GetExampleType(request);
        }
        
        public WAExample.SRExample.ResultMsg GetExampleType(string param) {
            WAExample.SRExample.GetExampleTypeRequest inValue = new WAExample.SRExample.GetExampleTypeRequest();
            inValue.Body = new WAExample.SRExample.GetExampleTypeRequestBody();
            inValue.Body.param = param;
            WAExample.SRExample.GetExampleTypeResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).GetExampleType(inValue);
            return retVal.Body.GetExampleTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.GetExampleItemResponse WAExample.SRExample.ServiceSoap.GetExampleItem(WAExample.SRExample.GetExampleItemRequest request) {
            return base.Channel.GetExampleItem(request);
        }
        
        public WAExample.SRExample.ResultMsg GetExampleItem(string param) {
            WAExample.SRExample.GetExampleItemRequest inValue = new WAExample.SRExample.GetExampleItemRequest();
            inValue.Body = new WAExample.SRExample.GetExampleItemRequestBody();
            inValue.Body.param = param;
            WAExample.SRExample.GetExampleItemResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).GetExampleItem(inValue);
            return retVal.Body.GetExampleItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.GetPowerInfoResponse WAExample.SRExample.ServiceSoap.GetPowerInfo(WAExample.SRExample.GetPowerInfoRequest request) {
            return base.Channel.GetPowerInfo(request);
        }
        
        public WAExample.SRExample.ResultMsg GetPowerInfo(string param1) {
            WAExample.SRExample.GetPowerInfoRequest inValue = new WAExample.SRExample.GetPowerInfoRequest();
            inValue.Body = new WAExample.SRExample.GetPowerInfoRequestBody();
            inValue.Body.param1 = param1;
            WAExample.SRExample.GetPowerInfoResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).GetPowerInfo(inValue);
            return retVal.Body.GetPowerInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.GetPowerInfo3Response WAExample.SRExample.ServiceSoap.GetPowerInfo3(WAExample.SRExample.GetPowerInfo3Request request) {
            return base.Channel.GetPowerInfo3(request);
        }
        
        public WAExample.SRExample.ResultMsg GetPowerInfo3(string code, string param1, string supposedData) {
            WAExample.SRExample.GetPowerInfo3Request inValue = new WAExample.SRExample.GetPowerInfo3Request();
            inValue.Body = new WAExample.SRExample.GetPowerInfo3RequestBody();
            inValue.Body.code = code;
            inValue.Body.param1 = param1;
            inValue.Body.supposedData = supposedData;
            WAExample.SRExample.GetPowerInfo3Response retVal = ((WAExample.SRExample.ServiceSoap)(this)).GetPowerInfo3(inValue);
            return retVal.Body.GetPowerInfo3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.GetExampleIDResponse WAExample.SRExample.ServiceSoap.GetExampleID(WAExample.SRExample.GetExampleIDRequest request) {
            return base.Channel.GetExampleID(request);
        }
        
        public WAExample.SRExample.ResultMsg GetExampleID(string code, string param1, string supposedData) {
            WAExample.SRExample.GetExampleIDRequest inValue = new WAExample.SRExample.GetExampleIDRequest();
            inValue.Body = new WAExample.SRExample.GetExampleIDRequestBody();
            inValue.Body.code = code;
            inValue.Body.param1 = param1;
            inValue.Body.supposedData = supposedData;
            WAExample.SRExample.GetExampleIDResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).GetExampleID(inValue);
            return retVal.Body.GetExampleIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.GetIEVersionCountResponse WAExample.SRExample.ServiceSoap.GetIEVersionCount(WAExample.SRExample.GetIEVersionCountRequest request) {
            return base.Channel.GetIEVersionCount(request);
        }
        
        public WAExample.SRExample.ResultMsg GetIEVersionCount(string version, string pageNum, string rowCount, string TimeStamp, string Sign, string supposedData) {
            WAExample.SRExample.GetIEVersionCountRequest inValue = new WAExample.SRExample.GetIEVersionCountRequest();
            inValue.Body = new WAExample.SRExample.GetIEVersionCountRequestBody();
            inValue.Body.version = version;
            inValue.Body.pageNum = pageNum;
            inValue.Body.rowCount = rowCount;
            inValue.Body.TimeStamp = TimeStamp;
            inValue.Body.Sign = Sign;
            inValue.Body.supposedData = supposedData;
            WAExample.SRExample.GetIEVersionCountResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).GetIEVersionCount(inValue);
            return retVal.Body.GetIEVersionCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.GetOldIEInfoListResponse WAExample.SRExample.ServiceSoap.GetOldIEInfoList(WAExample.SRExample.GetOldIEInfoListRequest request) {
            return base.Channel.GetOldIEInfoList(request);
        }
        
        public WAExample.SRExample.ResultMsg GetOldIEInfoList(string versionLevelFrom, string versionLevelTo, string pageNum, string rowCount, string TimeStamp, string Sign, string supposedData) {
            WAExample.SRExample.GetOldIEInfoListRequest inValue = new WAExample.SRExample.GetOldIEInfoListRequest();
            inValue.Body = new WAExample.SRExample.GetOldIEInfoListRequestBody();
            inValue.Body.versionLevelFrom = versionLevelFrom;
            inValue.Body.versionLevelTo = versionLevelTo;
            inValue.Body.pageNum = pageNum;
            inValue.Body.rowCount = rowCount;
            inValue.Body.TimeStamp = TimeStamp;
            inValue.Body.Sign = Sign;
            inValue.Body.supposedData = supposedData;
            WAExample.SRExample.GetOldIEInfoListResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).GetOldIEInfoList(inValue);
            return retVal.Body.GetOldIEInfoListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.GetIEVersionListResponse WAExample.SRExample.ServiceSoap.GetIEVersionList(WAExample.SRExample.GetIEVersionListRequest request) {
            return base.Channel.GetIEVersionList(request);
        }
        
        public WAExample.SRExample.ResultMsg GetIEVersionList(string versionLevelFrom, string versionLevelTo, string pageNum, string rowCount, string TimeStamp, string Sign, string supposedData) {
            WAExample.SRExample.GetIEVersionListRequest inValue = new WAExample.SRExample.GetIEVersionListRequest();
            inValue.Body = new WAExample.SRExample.GetIEVersionListRequestBody();
            inValue.Body.versionLevelFrom = versionLevelFrom;
            inValue.Body.versionLevelTo = versionLevelTo;
            inValue.Body.pageNum = pageNum;
            inValue.Body.rowCount = rowCount;
            inValue.Body.TimeStamp = TimeStamp;
            inValue.Body.Sign = Sign;
            inValue.Body.supposedData = supposedData;
            WAExample.SRExample.GetIEVersionListResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).GetIEVersionList(inValue);
            return retVal.Body.GetIEVersionListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WAExample.SRExample.PrepareForIE8DownloadingResponse WAExample.SRExample.ServiceSoap.PrepareForIE8Downloading(WAExample.SRExample.PrepareForIE8DownloadingRequest request) {
            return base.Channel.PrepareForIE8Downloading(request);
        }
        
        public WAExample.SRExample.ResultMsg PrepareForIE8Downloading(string Code, string TimeStamp, string Sign, string supposedData) {
            WAExample.SRExample.PrepareForIE8DownloadingRequest inValue = new WAExample.SRExample.PrepareForIE8DownloadingRequest();
            inValue.Body = new WAExample.SRExample.PrepareForIE8DownloadingRequestBody();
            inValue.Body.Code = Code;
            inValue.Body.TimeStamp = TimeStamp;
            inValue.Body.Sign = Sign;
            inValue.Body.supposedData = supposedData;
            WAExample.SRExample.PrepareForIE8DownloadingResponse retVal = ((WAExample.SRExample.ServiceSoap)(this)).PrepareForIE8Downloading(inValue);
            return retVal.Body.PrepareForIE8DownloadingResult;
        }
    }
}
